apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fast-api-poc
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: fast-api-poc-external-secret
    creationPolicy: Owner
  data:
  - secretKey: test-url
    remoteRef: 
      key: dev/argocd-poc/test-url

