apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml

resources:
  - argocd-namespace.yaml


patches:
- path: argocd-server-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server