image:
  repository: amazon/cloudwatch-agent
  tag: 1.247350.0b251780
  pullPolicy: IfNotPresent

clusterName: exciting-mushroom-1652034707

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

serviceAccount:
  create: true
  name:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::646203890422:role/eksctl-exciting-mushroom-1652034707-addon-ia-Role1-1ELD469GF1RL5

hostNetwork: false

nodeSelector: {}

tolerations: []

affinity: {}

# For bottlerocket OS (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-troubleshooting.html#ContainerInsights-troubleshooting-bottlerocket)
# containerdSockPath: /run/dockershim.sock 
containerdSockPath: /run/containerd/containerd.sock
