apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - cert-manager.yaml
  - default.yaml
  - external-dns.yaml
  - httpbin.yaml
  - nginx-ingress.yaml