apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: httpbin
  template:
    metadata:
    spec:
      containers:
      - name: httpbin
        image: httpbin