apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: httpbin
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: httpbin-external-secret
    creationPolicy: Owner
  data:
  - secretKey: test-url
    remoteRef: 
      key: dev/argocd-poc/test-url

